// react/src/layouts/Dashboard.js
import React from 'react';
import Gnb from 'components/Gnb';
import Header from 'components/Header';
import { Route } from 'react-router-dom';
import Work from 'pages/Work';
import 'scss/layouts/dashboard.scss';

const Dashboard = () => {
  return (
    <div className="dashboard-wrap">
      <Header />
      <div className="dashboard">
        <Gnb />
        <Route
          path="*"
          component={ Work }
        />
      </div>
    </div>
  );
};

export default Dashboard;

// vue/src/layouts/Dashboard.vue
<template>
  <div class="dashboard-wrap">
    <header />
    <div class="dashboard">
      <gnb />
      <router-view
        name="area"
      />
    </div>
  </div>
</template>
<script>
import 'scss/layouts/dashboard.scss';

export default {
  name: 'DashboardLayout',
  data() {
    return {};
  }
};
</script>
